### ISSUE TITLE
DTD

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#37]
I'm validating my files before uploading. Can you please provide and updated DTD?,Reporter,: Kristian

submitted via feedback button
USER-22

**Comment by samuele-mattiuzzo** [comment]
Hi Kristian, thanks for the feedback. This isn't really a question for the validator as much as it is for us in the Tech Team as it's Standard-related. The IATI standard comes with a [Schema](http://reference.iatistandard.org/203/schema/) definition (for Activities and Organisations) and we do not have a DTD, since it's an obsolete way of doing what the Schema does. If you need further assistance please get in touch at support@iatistandard.org

Thank you!

**Comment by Asken** [comment]
Sorry, you are correct. I'm validating against the schema. When I validate using http://reference.iatistandard.org/203/schema/downloads/iati-activities-schema.xsd I get non of the errors in https://test-validator.iatistandard.org/view/dqf/files/6b690656a45504d9c5461d136807280d.

If the schema had enumerations it would be great.

**Comment by samuele-mattiuzzo** [comment]
This test version of the validator is checking both Schema and [IATI Ruleset ](http://reference.iatistandard.org/203/rulesets/standard-ruleset/) so that's why you have a discrepancy there! Let's follow this one up via ZenDesk so that we can provide you with the guidance needed to navigate through the IATI ruleset!

**Comment by Asken** [comment]
I know about the rule set but I think you should exand the xsd a bit
further. You could for instance add code lists.

Kristian

Den ons 13 nov. 2019 11:49Samuele Mattiuzzo <notifications@github.com>
skrev:

**Comment by Asken** [comment]
Actually, I'll wait until the development documentation is in place so I can run the validator my self. I see you're using docker and xslt so that should not be a problem.

**Comment by samuele-mattiuzzo** [comment]
@Asken ok fantastic! What you're suggesting/asking is something more related to the standard than it is to the Validator (as the validator only applies what's in the standard, schema and ruleset)

If you do have suggestions around the standard https://discuss.iatistandard.org/ is the place, or for any question zendesk and support@iatistandard.org

will now close this issue! Thanks again for getting in touch and for testing the tool!

**Comment by rolfkleef** [comment]
Hi @Asken, a quick comment after closing: I agree that there is room to further develop the IATI schema to include some of the tests done here. (However, it won't automatically generate "human readable feedback".)

The validator engine does a couple of tasks, including schema validation, some xml error recovery, applying the business rules, and generating various output formats.

You could [try out the IATI-Rulesets XSLT as stand-alone](https://github.com/data4development/IATI-Rulesets) by applying the rules/iati.xslt stylesheet: it will take an IATI source file and add feedback messages embedded in a separate namespace.

Happy to talk more about developer docs and integration!
