### ISSUE TITLE
Error Message - Budget Period must not be longer than one year

### ISSUE THREAD

**Issue by rolfkleef** [data4development/IATI-data-validator#46]
We have projects which span more than one year and we don't necessarily break the budget into calendar years.  As such our budgets are consistent with the life of the project and thus are more than one year.  I read the related guidance and nowhere does it say that the budget must be broken down to calendar years when the projects themselves span more than a year.  I question this as an error.  At best it could or should be a warning, no?,Reporter,: Michelle Levesque - IOM,E-mail,: ,mylevesque@iom.int

submitted via feedback button
USER-24

**Comment by samuele-mattiuzzo** [comment]
Hello Michelle, thanks for getting in touch and for testing the tool!

I believe you are correct in your thinking process, although this is something more for consultation than it is for the tool itself!

`budget below 1 year` is a rule enforced in the Ruleset, so probably better to discuss these issues in Discuss? if the Validator is raising an error because your data does not pass the check, then it means the Validator works as intendend (applies existing rules to your files).

Whether the rules enforced are valid/correct/make sense, it's not tool-dependant, but more about the standard!

I'm closing this issue if that's ok with you, please feel free to comment any further and we can discuss and reopen this!

**Comment by amy-silcock** [comment]
Hi Michelle, 

Following on from Sam's point. Activity budgets must be 12 months or less, they do not have to conform to calendar years. When we discussed this recently with the community, the consensus was to guide publishers to use budget periods that were relevant to their organisation or life cycle of their activity.
