### ISSUE TITLE
Unable to see validation results

### ISSUE THREAD

**Issue by lozette** [data4development/IATI-data-validator#80]
**Describe the bug**
I uploaded an IATI XML file today to validate it, the URL is https://test-validator.iatistandard.org/view/dqf/files/c4eb26a7-cde6-4919-a050-5c105995dbbc

Unfortunately the results are never loaded, looking in the network tab on my browser (Chrome) I can see a 500 is being returned from 

Request URL: https://stage.dataworkbench.io/api/v1/iati-files/file/json/c4eb26a7-cde6-4919-a050-5c105995dbbc.json

which I assume is the problem!

**To Reproduce**
1. Go to https://test-validator.iatistandard.org/
2. Upload valid (I hope) XML file
3. Click through to validate

**Expected behavior**
I expected to be able to retrieve my validation results

**Screenshots**

**Desktop (please complete the following information):**
 - Device: MacBook Pro
 - OS: OSX
 - Browser Chrome latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PetyaKangalova** [comment]
Hi @lozette ! Thank you for flagging this. Would you be able to share the IATI XML file so that we can validate if we get the same error. You can send it to support@iatistandard.org  We are still in the process of testing the upload functionality.
@rolfkleef , if you are aware of any other errors/downtime of the validator that might be causing the error, please let us know.

**Comment by lozette** [comment]
Will do! Thank you!

**Comment by lozette** [comment]
Issue seems to be resolved, thank you for looking into it <3
